require "test_helper"

# The public apply URL's team slug: lead-editable like the rest of the team's
# details, validated (format + per-guild uniqueness), and never regenerated by
# a rename.
class TeamSlugTest < ActionDispatch::IntegrationTest
  setup do
    @guild = Guild.create!(id: 888_000_111_222_333_777, name: "Raid Server")
    ActsAsTenant.with_tenant(@guild) do
      @team = Team.create!(name: "Alpha", team_role_id: 1, officer_role_id: 2, review_channel_id: 3)
      TeamOfficer.create!(team: @team, discord_user_id: users(:member).discord_id,
                          discord_username: users(:member).username)
    end
  end

  test "a team lead can customize the slug" do
    sign_in_as users(:member), member: [ @guild ]

    patch guild_team_path(@guild, @team), params: { team: { slug: " raid-alpha " } }

    assert_redirected_to guild_team_path(@guild, @team)
    assert_equal "raid-alpha", @team.reload.slug
  end

  test "an invalid or taken slug is rejected with a friendly message" do
    ActsAsTenant.with_tenant(@guild) do
      Team.create!(name: "Bravo", team_role_id: 4, officer_role_id: 5, review_channel_id: 6)
    end
    sign_in_as users(:member), member: [ @guild ]

    patch guild_team_path(@guild, @team), params: { team: { slug: "Bad Slug!" } }
    assert_match(/lowercase letters/, flash[:alert])
    assert_equal "alpha", @team.reload.slug

    patch guild_team_path(@guild, @team), params: { team: { slug: "bravo" } }
    assert_match(/already taken/, flash[:alert])
    assert_equal "alpha", @team.reload.slug
  end

  test "plain members can't change the slug" do
    ActsAsTenant.with_tenant(@guild) { TeamOfficer.delete_all }
    sign_in_as users(:member), member: [ @guild ]

    patch guild_team_path(@guild, @team), params: { team: { slug: "sneaky" } }

    assert_redirected_to guild_path(@guild)
    assert_equal "alpha", @team.reload.slug
  end

  test "renaming via the web form keeps the slug" do
    sign_in_as users(:member), member: [ @guild ]

    patch guild_team_path(@guild, @team), params: { team: { name: "Alpha Reborn" } }

    @team.reload
    assert_equal "Alpha Reborn", @team.name
    assert_equal "alpha", @team.slug
  end
end
